# Form implementation generated from reading ui file 'c:\Users\karina\Documents\Docs\Python\Filler20 - Copy\designs\updater.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 315)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 240, 371, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 551, 321))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\karina\\Documents\\Docs\\Python\\Filler20 - Copy\\designs\\../startup.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.status = QtWidgets.QLabel(parent=self.centralwidget)
        self.status.setGeometry(QtCore.QRect(40, 200, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.label.raise_()
        self.progressBar.raise_()
        self.status.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Updater"))
        self.status.setText(_translate("MainWindow", "Ожидание.."))
